version: '3.5'

services:
  mongo:
    image: mongo
    container_name: pdfshare_mongo
    networks:
      pdfshare_proxy:
        ipv4_address: 172.28.0.4
  nginx:
    image: nginx:latest
    container_name: pdfshare_nginx
    volumes:
      - static_data:/var/www/static:rw
      - ${BOOKS_DIR}:/var/www/static/books:rw
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      pdfshare_proxy:
        ipv4_address: 172.28.0.3  
    depends_on:
      - pdfshare
  pdfshare:
    build:
      context: . #https://github.com/kingcobra2468/PDFShare.git#master:/
      dockerfile: Dockerfile
    image: pdfshare:latest
    container_name: pdfshare
    volumes:
      - ${BOOKS_DIR}:/home/server/pdfshare/app/static/books:rw
      - static_data:/home/server/pdfshare/app/static:rw
    expose:
      - "9000"
    environment:
      MONGO_HOST: "172.28.0.4"
    networks:
      pdfshare_proxy:
        ipv4_address: 172.28.0.2
    depends_on:
      - mongo
networks:
  pdfshare_proxy:
    name: pdfshare_proxy
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/29
volumes:
  static_data:
    name: static_data
