version: '3.5'

services:
  mongo:
    image: mongo
    container_name: pdfshare-mongo
    restart: always
    networks:
      pdfshare_proxy:
        ipv4_address: 172.28.0.4
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: pdfshare-nginx
    restart: always
    volumes:
      - ${PDF_DIR}:/var/www/static/books:rw
      - ${SSL_CERT_DIR:-/etc/ssl}:/etc/ssl:rw
      - pdf_covers:/var/www/static/covers:rw
      - ./nginx/${NGINX_CONF}:/etc/nginx/nginx.conf
    ports:
      - 7140:7140
    networks:
      pdfshare_proxy:
        ipv4_address: 172.28.0.3  
    depends_on:
      - pdfshare
  pdfshare:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pdfshare:latest
    container_name: pdfshare
    restart: always
    volumes:
      - ${PDF_DIR}:/home/server/pdfshare/app/static/books:rw
      - pdf_covers:/home/server/pdfshare/app/static/covers:rw
    expose:
      - "9000"
    environment:
      MONGO_HOST: "172.28.0.4"
    networks:
      pdfshare_proxy:
        ipv4_address: 172.28.0.2
    depends_on:
      - mongo
networks:
  pdfshare_proxy:
    name: pdfshare_proxy
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/29
volumes:
  pdf_covers:
    name: pdf_covers
