version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - static_data:/var/www/static
      - ~/Books:/var/www/static/books/  
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      pdfshare_proxy:
        ipv4_address: 172.28.0.3  
    depends_on:
      - pdfshare
  pdfshare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdfshare
    volumes:
      - ~/Books:/home/server/static/books/
      - static_data:/home/server/static
    #ports:
    #  - 9000:9000
    expose:
      - "9000"
    networks:
      pdfshare_proxy:
        ipv4_address: 172.28.0.2
networks:
  pdfshare_proxy:
    name: pdfshare_proxy
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/29
volumes:
  static_data:
